sort_tracker_viz_node:
  ros__parameters:
    # ROS parameters for the SORT tracker visualization node
    image_input_topic: "kitti/camera/color/left/image_raw"
    tracked_detections_input_topic: "sort_tracker/tracks"
    annotated_image_output_topic: "sort_tracker/image"
    queue_size: 10  # QoS parameter
    sync_queue_size: 10  # message_filters exact-time synchronizer queue size
